#!/usr/bin/env bash

set -e
readonly INSTALLATION_DIRECTORY=/opt/smalltalkci/
readonly DEFAULT_BRANCH=${INPUT_SMALLTALKCI_BRANCH:-master}
readonly DEFAULT_SOURCE=${INPUT_SMALLTALKCI_REPO:-hpi-swa/smalltalkCI}

echo "::group::Downloading and extracting smalltalkCI"
curl \
  --location "https://github.com/${DEFAULT_SOURCE}/archive/${DEFAULT_BRANCH}.tar.gz" \
  --output /tmp/smalltalkCI.tar.gz
tar -xzvf /tmp/smalltalkCI.tar.gz -C ${INSTALLATION_DIRECTORY} --strip-components=1
echo "::endgroup::"

readonly SMALLTALKCI_SPEC=${INPUT_SPEC:-.smalltalk.ston}
readonly SMALLTALKCI_SPEC_FULL_PATH="${GITHUB_WORKSPACE}/${SMALLTALKCI_SPEC}"
readonly COVERAGE_PATH="$(dirname "${SMALLTALKCI_SPEC_FULL_PATH}")/coverage"

echo "::group::Preparing coverage directory"
mkdir -p "${COVERAGE_PATH}"
chmod -R a+rwx "${COVERAGE_PATH}"
echo "::endgroup::"

echo "::group::Running smalltalkCI"

"${INSTALLATION_DIRECTORY}/run.sh" \
  -s Pharo64-10 \
  --image /opt/pharo/Pharo.image \
  --vm /opt/pharo/pharo-vm \
  "${SMALLTALKCI_SPEC_FULL_PATH}"

echo "::endgroup::"

exit 0
